# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            yang
tagline:          ''
description:      '『he looks like a dog so』 『because he is a PM』'
url:              http://yanghg.github.io
baseurl: /blog
author:
  name:           'yang'
  email:          yanghong2014@u.northwestern.edu

paginate:      5

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : cellier-me


