# Dependencies
markdown:         redcarpet
highlighter:      pygments
excerpt_separator: <span class="more"></span>

# Permalinks
permalink:        pretty

# Setup
title:            yang
tagline:          ''
description:      '『to see the world as it is, and to love it』'
url:              http://yanghg.github.io
baseurl: /blog
author:
  name:           'yang'
  email:          yanghong2014@u.northwestern.edu

paginate:      5

# Custom vars
version:          0.0.1

# Comments
comments :
    provider : duoshuo
    duoshuo :
          short_name : yanghg


